Repository Historia-Clinica-La-Rioja/historia_clinica_LR, pull requests merged in 2023-11, with the labels that each got.

#26 [Feature] added odontogram references to odontology section
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/odontologia/components/odontogram/odontogram.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/odontologia/components/odontogram/odontogram.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/odontologia/components/odontogram/odontogram.component.ts
  front-end/apps/projects/hospital/src/assets/odontogram-references/1.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/10.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/11.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/12.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/13.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/14.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/15.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/16.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/17.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/18.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/19.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/2.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/20.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/21.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/22.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/23.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/3.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/4.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/5.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/6.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/7.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/8.png
  front-end/apps/projects/hospital/src/assets/odontogram-references/9.png
Labels: enhancement, frontend

#22 Filtro de edad/Age Filter
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.ts
Labels: enhancement, frontend

#28 FIXED JSON FRAIL SCALE
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.ts
Labels: bug, enhancement, frontend

#20 Modificación de fechas en Reportes Provinciales
  back-end/hospital-api/src/main/java/net/pladema/generalreports/service/impl/GeneralReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/nursingreports/service/impl/NursingReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/olderadultsreports/service/impl/OlderAdultsReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/programreports/service/impl/ProgramReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/reportformat/DateFormat.java
Labels: bug, enhancement, backend

#34 Fixed/studies adult
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/pop-up/estudios-popup.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.scss
Labels: bug, enhancement, frontend

#39 Fixed/adult-icon
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
  front-end/apps/projects/hospital/src/assets/images/icon_adultomayor.png
Labels: enhancement, frontend

#41 Fixed/question-frail
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.scss
  front-end/apps/projects/hospital/src/assets/images/formula-frail.png
Labels: enhancement, frontend

#42 FIXED - Agregar evaluacion y Ver ultima evaluacion
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
Labels: enhancement, frontend

#56 [Feature] added pregnant people reports to backend
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/controller/PregnantPeopleReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantAttentionsConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantControlsConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantPeopleReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/service/PregnantPeopleReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/service/impl/PregnantPeopleReportExcelServiceImpl.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#57 [Feature] added pregnant people reports to frontend
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/pregnantpeople-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja.component.html
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja.module.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/constants/pregnantpeople-report-types.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/reportes-personagestante.component.html
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/reportes-personagestante.component.scss
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/reportes-personagestante.component.ts
Labels: enhancement, frontend

#54 Added functionality in question final
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.html
Labels: enhancement, frontend

#52 Fixed bug button and tittle change
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/pop-up/estudios-popup.component.html
Labels: bug, enhancement, frontend

#53 Feat/edmonton
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/edmonton.service.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/pop-up/estudios-popup.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/pop-up/estudios-popup.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/pop-up/estudios-popup.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
Labels: enhancement, frontend

#61 [Fix] updated 'sap-table' section
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/tabla-sap/tabla-sap.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/tabla-sap/tabla-sap.component.scss
Labels: bug, enhancement, frontend
