Repository Historia-Clinica-La-Rioja/historia_clinica_LR, pull requests merged in 2024-07, with the labels that each got.

#167 FIX VISUALIZACION DE PUNTAJE - FRAIL/EDMONTON
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.ts
Labels: bug, frontend

#168 fix: add autofill to PDFs where values aren't received and checkboxes…
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/familybg_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/physicalperformance_reports.html
Labels: enhancement, backend

#169 FIX ADULTO MAYOR Y TEXTO DE DESEMPEÑO FISICO
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.scss
Labels: bug, enhancement, frontend

#170 [ Fix ] Correcciones en cuestionario "Prueba corta de desempeño físico" - Adulto Mayor - Limites de tiempo
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-desempeno/input-desempeno.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-desempeno/input-desempeno.component.ts
Labels: bug, enhancement, frontend

#171 [Feature] update configuration for 2.21.9 release
  back-end/pom-parent.xml
Labels: documentation, enhancement

#172 fix: change 'recupero odontologico' query because it was identical to…
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#174 [Feature] update configuration for 2.21.10 release
  back-end/pom-parent.xml
Labels: documentation, enhancement
