Repository Historia-Clinica-La-Rioja/historia_clinica_LR, pull requests merged in 2024-10, with the labels that each got.

#210 Feat: pregnant people and epidemiology reports
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/controller/EpidemiologyReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/controller/EpidemiologyReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/EpidemiologyReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/EpidemiologyReportsQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/service/EpidemiologyReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/service/EpidemiologyReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/service/impl/EpidemiologyReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/GeneralReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/controller/NursingReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/repository/NursingOutpatientConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/service/NursingReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/controller/OdontologicalReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/service/OdontologicalReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/controller/OlderAdultReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/service/OlderAdultReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/controller/PregnantPeopleReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/controller/PregnantPeopleReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantAttentionsConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantControlsConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantPeopleReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantPeopleReportsQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/service/PregnantPeopleReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/service/PregnantPeopleReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/service/impl/PregnantPeopleReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/controller/ProgramReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/service/ProgramReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/domain/service/ReportExcelUtilsService.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#209 BACKGROUND FAMILY GET
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/get-backgrounds/get-backgrounds.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/get-backgrounds/get-backgrounds.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/get-backgrounds/get-backgrounds.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.html
  front-end/apps/projects/hospital/src/assets/icons/icon_cuestionario.png
Labels: enhancement, frontend

#213 [Feature] update configuration for 2.24.10 release
  back-end/pom-parent.xml
Labels: documentation, enhancement

#216 [Fix] Corrección de error de tipeo en "Rutas provinciales - Asistenciales"
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.html
Labels: bug, frontend

#218 feat: add gerontological assessments report (query & code implementations)
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/controller/OdontologicalReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/controller/OlderAdultReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/repository/GerontologicalAssessmentsConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/repository/OlderAdultReportsQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/service/OlderAdultReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/repository/ReportsRepositoryUtils.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#219 Fix: nursing outpatient and medicines prescription
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/MedicinesPrescriptionConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/GeneralReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/controller/NursingReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/service/NursingReportsExcelService.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend
