Repository Historia-Clinica-La-Rioja/historia_clinica_LR, pull requests merged in 2024-09, with the labels that each got.

#202 FIX AND FEATURES BACKGROUNDS FAMILY
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.ts
Labels: bug, enhancement, frontend

#201 feat: odontological and older adults reports
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/controller/NursingReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/controller/OdontologicalReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/controller/OdontologicalReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/repository/OdontologicalReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/repository/OdontologicalReportsQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/service/OdontologicalReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/service/OdontologicalReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/service/impl/OdontologicalReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/controller/OlderAdultReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/controller/OlderAdultsReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/repository/OlderAdultReportsQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/repository/OlderAdultsReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/service/OlderAdultReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/service/OlderAdultsReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/service/impl/OlderAdultsReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/controller/ProgramReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/DateFormat.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#204 [Feature] added feature flag to enable/disable 'ANTECEDENTES' tab
  back-end/sgx-shared/src/main/java/ar/lamansys/sgx/shared/featureflags/AppFeature.java
  back-end/sgx-shared/src/main/java/ar/lamansys/sgx/shared/flavor/instances/HospitalsFeatureStates.java
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.html
Labels: enhancement, backend, frontend

#205 [Fix] data format fixed in evolution note popup
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/nota-de-evolucion-dock-popup/nota-de-evolucion-dock-popup.component.ts
Labels: bug, enhancement, frontend

#206 [Fix] fix query OdontologyConsultationDetail
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: bug, backend

#203 feat: program reports update
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/controller/ProgramReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/ProgramReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/ProgramReportsQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/service/ProgramReportsExcelService.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#207 feat: update family background questionnaire html template
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/familybg_reports.html
Labels: enhancement, backend

#208 [Feature] update configuration for 2.24.9 release
  back-end/pom-parent.xml
Labels: documentation, enhancement
