Repository Historia-Clinica-La-Rioja/historia_clinica_LR, pull requests merged in 2024-04, with the labels that each got.

#107 [Feature] improvements in downloading FRAIL forms
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/fragility-test.service.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/get-frail/get-frail.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/get-frail/get-frail.component.ts
Labels: bug, enhancement, frontend

#100 Formulario de Desempeño fisico
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/physical-performance.service.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/pop-up/estudios-popup.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-desempeno/input-desempeno.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-desempeno/input-desempeno.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-desempeno/input-desempeno.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-point/input-point.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-point/input-point.component.ts
  front-end/apps/projects/hospital/src/assets/icons/icon-06.png
  front-end/apps/projects/hospital/src/assets/icons/icon-07.png
  front-end/apps/projects/hospital/src/assets/icons/icon-08.png
  front-end/apps/projects/hospital/src/assets/icons/icon-09.png
  front-end/apps/projects/hospital/src/assets/icons/icon-10.png
  front-end/apps/projects/hospital/src/assets/icons/icon-11.png
  front-end/apps/projects/hospital/src/assets/icons/icon-12.png
  front-end/apps/projects/hospital/src/assets/icons/icon-13.png
Labels: enhancement, frontend

#108 [Fix] provincial reports fixed
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/ComplementaryStudiesConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/DiabeticHypertensionConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/impl/GeneralReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/service/impl/NursingReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/controller/OdontologicalReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/repository/OdontologicalProceduresConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/repository/OdontologyConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/service/OdontologicalReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/service/impl/OdontologicalReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/repository/OlderAdultsHospitalizationConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/repository/OlderAdultsOutpatientConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/service/impl/OlderAdultsReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/service/impl/PregnantPeopleReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/controller/ProgramReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/EpidemiologyTwoConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/OdontologicalConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/ProgramReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/RecuperoGeneralConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/RecuperoOdontologicoConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/SumarGeneralConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/service/ProgramReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/service/impl/ProgramReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/DateFormat.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: bug, enhancement, backend

#112 [Feature] update emergency report
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/EmergencyConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/impl/GeneralReportExcelServiceImpl.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#114 [Feature] add epidemiology reports
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/controller/EpidemiologyReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/CompleteDengueConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/DenguePatientControlConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/EpidemiologyReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/service/EpidemiologyReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/service/impl/EpidemiologyReportExcelServiceImpl.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#116 [Frontend] Reportes de Dengue
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/dengue-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reporte-dengue/constants/dengue-report-types.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reporte-dengue/reporte-dengue.component.html
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reporte-dengue/reporte-dengue.component.scss
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reporte-dengue/reporte-dengue.component.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja.component.html
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja.module.ts
Labels: enhancement, frontend

#115 Edmonton Form
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/edmonton.service.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
Labels: bug, enhancement, frontend

#118 [Frontend] - Diseño de módulo de "Rutas provinciales"
  front-end/apps/projects/hospital/src/app/app.module.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
  front-end/apps/projects/hospital/src/app/modules/institucion/constants/menu.ts
  front-end/apps/projects/hospital/src/app/modules/institucion/institucion-routing.module.ts
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas-routing.module.ts
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.html
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.scss
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.ts
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.module.ts
  front-end/apps/projects/hospital/src/assets/i18n/es-AR.json
  front-end/apps/projects/hospital/src/assets/icons/DR-active-icon.png
  front-end/apps/projects/hospital/src/assets/icons/DT-active-icon.png
  front-end/apps/projects/hospital/src/assets/rutas-lr/diagramas-de-ruta-pdf/Hipertensión-RutaAsistencial.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DR1.jpg
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DT1.jpg
Labels: enhancement, frontend

#113 Feat: add POST and GET endpoints for the errata feature
  back-end/hospital-api/src/main/java/net/pladema/errata/common/dto/ErrataRequestDTO.java
  back-end/hospital-api/src/main/java/net/pladema/errata/common/repository/ErrataRepository.java
  back-end/hospital-api/src/main/java/net/pladema/errata/common/repository/entity/Errata.java
  back-end/hospital-api/src/main/java/net/pladema/errata/general/endpoints/controller/ErrataController.java
  back-end/hospital-api/src/main/java/net/pladema/errata/general/endpoints/service/ErrataService.java
Labels: enhancement, backend

#106 Feat: create 'update questionnaire' PUT endpoint
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/dto/UpdateResponseDTO.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/update/controller/UpdateQuestionnaireController.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/update/domain/service/UpdateQuestionnaireService.java
Labels: enhancement, backend
