Repository Historia-Clinica-La-Rioja/historia_clinica_LR, pull requests merged in 2024-08, with the labels that each got.

#177 Feature/rutas larioja
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.ts
  front-end/apps/projects/hospital/src/assets/rutas-lr/diagramas-de-ruta-pdf/ActividadFisica-RutaAsistencial.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/diagramas-de-ruta-pdf/Odontologia-RutaAsistencial.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/documentos-tecnicos-pdf/ActividadFisica-RutaAsistencial-DocumentoTecnico.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/documentos-tecnicos-pdf/Odontología-RutaAsistencial-DocumentoTecnico.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DR-AF.png
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DR-O.png
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DT-AF.png
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DT-O.png
Labels: documentation, enhancement, frontend

#181 [Feature] fix provincial reports in frontend
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/general-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/nursing-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/odontology-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/olderadult-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/pregnantpeople-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/program-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-adultomayor/reportes-adultomayor.component.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-enfermeria/reportes-enfermeria.component.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-generales/reportes-generales.component.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-odontologia/reportes-odontologia.component.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/reportes-personagestante.component.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-programas/reportes-programas.component.ts
Labels: bug, enhancement, frontend

#183 fix/questionnaire-logging
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/create/controller/CreateQuestionnaireController.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/create/domain/service/CreateQuestionnaireService.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/domain/service/GetAllService.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java
Labels: enhancement, backend

#179 feat: general and nursing report refactors, medicines prescription report
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/EmergencyConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/GeneralReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/GeneralReportsQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/MedicinesPrescriptionConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/GeneralReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/GeneralReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/impl/GeneralReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/controller/NursingReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/controller/NursingReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/repository/NursingReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/repository/NursingReportsQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/service/NursingReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/service/NursingReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/service/impl/NursingReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/controller/ProgramReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/service/ProgramReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/DateFormat.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/domain/service/ReportExcelUtilsService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/repository/ReportsRepositoryUtils.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#185 BACKGROUNDS FAMILY FORM
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/antecedentes.service.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.html
Labels: enhancement, frontend

#189 [Frontend] Implementación del Reporte de Prescripciones de Medicamentos
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/general-reports.service.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-generales/constants/general-report-types.ts
  front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-generales/reportes-generales.component.ts
Labels: enhancement, frontend

#186 Feat: institution in questionnaire & medicines prescription report title
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/repository/entity/QuestionnaireResponse.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/create/controller/CreateQuestionnaireController.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/create/domain/service/CreateQuestionnaireService.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/edmonton_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/familybg_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/frail_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/physicalperformance_reports.html
Labels: enhancement, backend
