Repository Historia-Clinica-La-Rioja/historia_clinica_LR, pull requests merged in 2024-05, with the labels that each got.

#119 [Fix] update api-model
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
Labels: bug, enhancement, frontend

#120 Feature and fix endmonton form
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
Labels: bug, enhancement, frontend

#121 feat: add author-restricted filter to errata creation endpoint
  back-end/hospital-api/src/main/java/net/pladema/errata/common/dto/ErrataRequestDTO.java
  back-end/hospital-api/src/main/java/net/pladema/errata/common/repository/CustomDocumentRepository.java
  back-end/hospital-api/src/main/java/net/pladema/errata/general/endpoints/service/ErrataService.java
Labels: enhancement, backend

#134 [Feature] add sumar public-api
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/application/fetchconsultationsbyinstitutionid/FetchConsultationsByInstitutionId.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/application/port/out/ConsultationDetailDataStorage.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/domain/ConsultationDetailDataBo.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/domain/exceptions/BadConsultationFormatException.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/domain/exceptions/ConsultationNotFoundException.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/domain/exceptions/ConsultationRequestException.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/input/rest/SumarApiController.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/input/rest/dto/ConsultationDetailDataDto.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/input/rest/mapper/ConsultationMapper.java
  back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/output/ConsultationDetailDataStorageImpl.java
  back-end/hospital-public-api/src/main/resources/META-INF/orm.xml
Labels: enhancement, backend

#136 [Feature] update configuration for 2.16.3 release
  back-end/pom-parent.xml
Labels: documentation, enhancement

#137 [Fix] remove duplicated section
  front-end/apps/projects/hospital/src/app/modules/institucion/constants/menu.ts
Labels: bug, enhancement, frontend

#139 [Fix] change the repositoryPerson method
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java
Labels: bug, enhancement, backend

#132 Fix: reports pdf formatting & extract code duplicate
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/domain/service/QuestionnaireUtilsService.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/domain/service/GetAllService.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/edmonton_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/familybg_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/frail_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/physicalperformance_reports.html
Labels: enhancement, backend

#133 GET EDMONTON
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/edmonton.service.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/pop-up/latest-studies/latest-studies.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/get-edmonton/get-edmonton.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/get-edmonton/get-edmonton.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/get-edmonton/get-edmonton.component.ts
Labels: enhancement, frontend

#140 [Feature] update configuration for 2.16.4 release
  back-end/pom-parent.xml
Labels: documentation, enhancement

#141 GET AND FIX - DESEMPEÑO FISICO
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/physical-performance.service.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/pop-up/latest-studies/latest-studies.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/get-physical-performance/get-physical-performance.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/get-physical-performance/get-physical-performance.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/get-physical-performance/get-physical-performance.component.ts
Labels: enhancement, frontend

#142 Fix: questionnaires professional details' fetching
  back-end/hospital-api/src/main/java/net/pladema/errata/common/dto/ErrataRequestDTO.java
  back-end/hospital-api/src/main/java/net/pladema/errata/general/endpoints/service/ErrataService.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/domain/service/QuestionnaireUtilsService.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/repository/entity/QuestionnaireResponse.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/controller/GetAllController.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/domain/service/GetAllService.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java
Labels: enhancement, backend

#143 Feat: modify final sections of assessments HTML template to be the same
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/edmonton_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/frail_reports.html
  back-end/hospital-api/src/main/resources/templates/flavors/minsal/physicalperformance_reports.html
Labels: enhancement, backend

#144 Actualización en el módulo de "Rutas provinciales"
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.ts
  front-end/apps/projects/hospital/src/assets/rutas-lr/diagramas-de-ruta-pdf/EPOC-RutaAsistencial.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/diagramas-de-ruta-pdf/Hipertension-RutaAsistencial.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/documentos-tecnicos-pdf/Hipertension-RutaAsistencial-DocumentoTecnico.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DR2.jpg
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DT1.png
Labels: enhancement, frontend

#145 [Feature] add dialog alert for 'Adulto Mayor' questionnaires
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/alert-dialog/alert-dialog.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/alert-dialog/alert-dialog.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/alert-dialog/alert-dialog.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/get-physical-performance/get-physical-performance.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/get-edmonton/get-edmonton.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/get-frail/get-frail.component.ts
Labels: enhancement, frontend

#146 [Feature] update configuration for 2.16.5 release
  back-end/pom-parent.xml
Labels: documentation, enhancement
