Repository Historia-Clinica-La-Rioja/historia_clinica_LR, pull requests merged in 2024-06, with the labels that each got.

#149 [Feature] update 'get-all-questionnaires' controller
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/repository/QuestionnaireResponseRepository.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/repository/entity/QuestionnaireResponse.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/controller/GetAllController.java
  back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/domain/service/GetAllService.java
Labels: enhancement, backend

#150 Fix result in desempeño fisico
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.ts
Labels: enhancement, frontend

#152 Feature pestaña adulto mayor
  front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
  front-end/apps/projects/hospital/src/app/modules/api-rest/services/fragility-test.service.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.ts
  front-end/apps/projects/hospital/src/assets/icons/directions_run_24dp_FILL0_wght400_GRAD0_opsz24.svg
  front-end/apps/projects/hospital/src/assets/icons/elderly_woman_24dp_FILL0_wght400_GRAD0_opsz24.svg
  front-end/apps/projects/hospital/src/assets/icons/receipt_long_24dp_FILL0_wght400_GRAD0_opsz24.svg
Labels: enhancement, frontend

#156 Desempeño fisico y nueva interface
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.ts
Labels: enhancement, frontend

#155 FIX edmonton
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.html
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
Labels: bug, frontend

#157 Nuevo archivo "Documento técnico" para la ruta asistencial "EPOC"
  front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.ts
  front-end/apps/projects/hospital/src/assets/rutas-lr/documentos-tecnicos-pdf/EPOC-RutaAsistencial-DocumentoTecnico.pdf
  front-end/apps/projects/hospital/src/assets/rutas-lr/miniatures/DT-EPOC.jpg
Labels: documentation, enhancement, frontend

#151 feat: reports improvement
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/controller/ProgramReportController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/controller/ProgramReportsController.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/OdontologicalConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/ProgramReportQueryFactory.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/RecuperoGeneralConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/repository/SumarGeneralConsultationDetail.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/service/ProgramReportExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/service/ProgramReportsExcelService.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/programreports/service/impl/ProgramReportExcelServiceImpl.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/DateFormat.java
  back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/domain/service/ReportExcelUtilsService.java
  back-end/hospital-api/src/main/resources/META-INF/orm.xml
Labels: bug, enhancement, backend

#158 [ Fix ] Modificación de textos en cuestionario "Desempeño físico"
  front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
Labels: bug, enhancement, frontend

#159 [Feature] update configuration for 2.21.8 release
  back-end/pom-parent.xml
Labels: documentation, enhancement
